### ISSUE TITLE
Improve installation docs

### ISSUE THREAD

**Issue by ergonlogic** [veda-consulting/uk.co.vedaconsulting.mosaico#240]
When I try to use the Mosaico features (by visiting `/civicrm/a/#/mailing/1`), I receive the following error:

> Mosaico cannot be displayed because this system does not meet all requirements.
> For details, check the System Status.

Visiting the status page, displays the following error: 

> Mosaico: Packages are missing
> Mosaico requires dependencies in its "packages" folder. Please consult the README.md for current installation instructions.

Tracking down the code that's outputting this error led to [this check](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/2.x/mosaico.php#L202), which is looking for the presence of the following files:

- `packages/mosaico/dist/mosaico.min.js`
- `packages/mosaico/dist/vendor/jquery.min.js`

Neither of these appear to be bundled into the [latest release tarball](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/releases/tag/2.0-beta3).

**Comment by ergonlogic** [comment]
It turns out that I had built the codebase pointing to the github-hosted release tarball, rather than the [one hosted on civicrm.org](https://civicrm.org/extensions/email-template-builder). I guess I was just being dense, but it may be worthwhile pointing this out in the installation docs.

For those using Drush Make, the following makefile should get you to a working minimalist Drupal/CiviCRM/Mosaico codebase.

```yml
core: 7.x
api: '2' 
 
defaults: 
  libraries: 
    download: 
      type: git 
    destination: modules/contrib/civicrm/extensions 
    overwrite: '1' 
  projects:
    subdir: contrib

projects:
  drupal:
    type: core
  civicrm:
    download:
      type: get
      url: 'https://download.civicrm.org/civicrm-4.7.27-drupal.tar.gz'

libraries:
  # Mosaico & dependencies   
  org.civicrm.shoreditch: 
    download: 
      url: https://github.com/civicrm/org.civicrm.shoreditch.git 
  org.civicrm.flexmailer: 
    download: 
      url: https://github.com/civicrm/org.civicrm.flexmailer.git 
  uk.co.vedaconsulting.mosaico: 
    download: 
      type: "file" 
      url: https://download.civicrm.org/extension/uk.co.vedaconsulting.mosaico/latest/uk.co.vedaconsulting.mosaico-latest.zip
```
