### ISSUE TITLE
Why is subject field so short on 3.5?

### ISSUE THREAD

**Issue by themak1985** [veda-consulting/uk.co.vedaconsulting.mosaico#642]
Why is the subject field so small since 3.5?

![Screenshot 2024-04-15 at 1 58 04 PM](https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/assets/28904266/a12e0ef9-a470-47fc-b036-5e9d375c3b6c)

While we are on the subject of size, why is the template thumbnail so big?

![Screenshot 2024-04-15 at 2 00 38 PM](https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/assets/28904266/5916fbde-4cd4-4c24-aa35-f3125186aed5)

**Comment by themak1985** [comment]
Any chance this can be fixed, or is there a quick fix we can make on the side? Mainly the subject field.

**Comment by demeritcowboy** [comment]
I'm using this in the site theme's css:
```css
#bootstrap-theme crm-mosaico-subject-list input#inputSubject {
  display: block;
  width: 100%;
}
```
